# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sik\'s_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sik's_App

  # Pods for socialLogin
  
  pod 'GoogleSignIn'

end
